name: Publish Mod    #The name of your GitHub Action on github.com

on: [ pull_request, workflow_dispatch ]           #When your GitHub Action will be executed ('pull_request' -> on every Merge(/Pull) Request; 'workflow_dispatch' -> allows manual execution through github.com

env:                                              #Environment variables that can later be referenced using ${{ env.MINECRAFT_VERSION }}. These are useful for repeating information and allow for quick changes for new mod updates
  MINECRAFT_VERSION: 1.20.1
  JAVA_VERSION: 17
  MOD_VERSION: 1.8.5


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{env.JAVA_VERSION}}

      - name: Build
        run: gradle clean build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}

          github-token: ${{ secrets.G_TOKEN }}
          github-tag: "${{env.MOD_VERSION}}+${{env.MINECRAFT_VERSION}}"

          name: "${{env.MOD_VERSION}}+${{env.MINECRAFT_VERSION}}"
          version: "${{env.MOD_VERSION}}+${{env.MINECRAFT_VERSION}}"
          version-type: release

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"