name: Publish Mod

on: [ pull_request, workflow_dispatch ]

env:
  MOD_VERSION: 2.3.1

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            21
            25

      - name: Build All Versions
        run: bash ./gradlew buildAndCollect

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.G_TOKEN }}
          tag_name: ${{ env.MOD_VERSION }}
          name: ${{ env.MOD_VERSION }}
          files: build/libs/${{ env.MOD_VERSION }}/*.jar

      - name: Publish 1.21.5
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/one-click-crafting-${{ env.MOD_VERSION }}+1.21.5*.jar
          name: "${{ env.MOD_VERSION }}+1.21.5"
          version: "${{ env.MOD_VERSION }}+1.21.5"
          version-type: release
          loaders: fabric
          game-versions: "1.21.5"
          java: 21
          dependencies: |
            fabric-api
            modmenu
            yacl

      - name: Publish 1.21.6
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/one-click-crafting-${{ env.MOD_VERSION }}+1.21.6*.jar
          name: "${{ env.MOD_VERSION }}+1.21.6"
          version: "${{ env.MOD_VERSION }}+1.21.6"
          version-type: release
          loaders: fabric
          game-versions: "1.21.6"
          java: 21
          dependencies: |
            fabric-api
            modmenu
            yacl

      - name: Publish 1.21.7
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/one-click-crafting-${{ env.MOD_VERSION }}+1.21.7*.jar
          name: "${{ env.MOD_VERSION }}+1.21.7"
          version: "${{ env.MOD_VERSION }}+1.21.7"
          version-type: release
          loaders: fabric
          game-versions: "1.21.7"
          java: 21
          dependencies: |
            fabric-api
            modmenu
            yacl

      - name: Publish 1.21.8
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/one-click-crafting-${{ env.MOD_VERSION }}+1.21.8*.jar
          name: "${{ env.MOD_VERSION }}+1.21.8"
          version: "${{ env.MOD_VERSION }}+1.21.8"
          version-type: release
          loaders: fabric
          game-versions: "1.21.8"
          java: 21
          dependencies: |
            fabric-api
            modmenu
            yacl      

      - name: Publish 1.21.9
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/one-click-crafting-${{ env.MOD_VERSION }}+1.21.9*.jar
          name: "${{ env.MOD_VERSION }}+1.21.9"
          version: "${{ env.MOD_VERSION }}+1.21.9"
          version-type: release
          loaders: fabric
          game-versions: "1.21.9"
          java: 21
          dependencies: |
            fabric-api
            modmenu
            yacl      

      - name: Publish 1.21.10
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/one-click-crafting-${{ env.MOD_VERSION }}+1.21.10*.jar
          name: "${{ env.MOD_VERSION }}+1.21.10"
          version: "${{ env.MOD_VERSION }}+1.21.10"
          version-type: release
          loaders: fabric
          game-versions: "1.21.10"
          java: 21
          dependencies: |
            fabric-api
            modmenu
            yacl

      - name: Publish 1.21.11
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/one-click-crafting-${{ env.MOD_VERSION }}+1.21.11*.jar
          name: "${{ env.MOD_VERSION }}+1.21.11"
          version: "${{ env.MOD_VERSION }}+1.21.11"
          version-type: release
          loaders: fabric
          game-versions: "1.21.11"
          java: 21
          dependencies: |
            fabric-api
            modmenu
            yacl

      - name: Publish 26.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/one-click-crafting-${{ env.MOD_VERSION }}+26.1*.jar
          name: "${{ env.MOD_VERSION }}+26.1"
          version: "${{ env.MOD_VERSION }}+26.1"
          version-type: release
          loaders: fabric
          game-versions: "26.1.x"
          java: 25
          dependencies: |
            fabric-api
            modmenu
            yacl
